-- Sample feed for local development. Safe to run repeatedly.
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f seed.sql

TRUNCATE post_likes, post_saves, posts RESTART IDENTITY;

INSERT INTO posts (id, video_url, author_id, author_handle, author_display_name, author_emoji, author_is_verified, caption, music, likes, comments_count, saves, shares, created_at) VALUES
('hogsmeade-welcome', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8', 'dumbledore', '@dumbledore', 'Albus', '🧙', TRUE, 'ยินดีต้อนรับสู่ห้องรวมเพื่อน มาเล่นฟีดคลิปสั้นกันเถอะ 🧹', 'Hedwig''s Theme - John Williams', 128400, 2310, 9820, 1204, NOW() - INTERVAL '14 minutes'),
('quidditch-practice', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8', 'mcgonagall', '@mcgonagall', 'Minerva', '🐱', TRUE, 'ซ้อนควิดดิชนีครั้งที่ 12 ใครซ้อนเป็นบอกบิ๊ก', 'Quidditch March - choir cover', 45900, 812, 3004, 640, NOW() - INTERVAL '13 minutes'),
('hogsmeade-night', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8', 'snape', '@snape', 'Severus', '🧛', FALSE, 'เดินคนเดียวในฮอกส์เมียดตอนกลางคืน... เสียงอะไรนั้นคืออะไร 🔪', 'original sound - the.snape', 87250, 5640, 12480, 3410, NOW() - INTERVAL '12 minutes'),
('common-room-reading', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_example_hevc/main.m3u8', 'hermione', '@hermione', 'Hermione', '📚', TRUE, 'อ่านหนังสือ 420 เล่มจบใน 7 วัน 📖 challenge accepted', 'Librarian Vibes - lofi', 231000, 12050, 41300, 18920, NOW() - INTERVAL '11 minutes'),
('diagon-alley', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_ts/master.m3u8', 'harry', '@harry', 'Harry', '⚡', TRUE, 'เดินซื้อของที่ไดแอกอนอลลีย์ครั้งแรกกันเถอะ 🪄', 'Diagon Alley - ambient', 512800, 24710, 63120, 41050, NOW() - INTERVAL '10 minutes'),
('greenhouse-ritual', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8', 'sprout', '@sprout', 'Pomona', '🌿', FALSE, 'ถ้าผักโตเร็วผิดปกติ แปลว่ามีคนใส่มันกินเว้นแว่น 👓', 'Greenhouse Groove', 15400, 402, 1180, 205, NOW() - INTERVAL '9 minutes'),
('owl-post', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8', 'hedwig', '@hedwig', 'Hedwig', '🦉', TRUE, 'จดหมายด่วนจากนกฮูว์ ถึงปลายทางที่หายไป 📨', 'Owl Post OST', 64300, 1910, 8420, 1130, NOW() - INTERVAL '8 minutes'),
('astronomy-tower', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8', 'flitwick', '@flitwick', 'Filius', '🪄', FALSE, 'เรียนดูดาวรอบเก้า คืนนี้ดาวพยากรณ์ไม่ดีเท่าไร่ 🌌', 'Astronomy Ambient', 38120, 990, 2760, 420, NOW() - INTERVAL '7 minutes'),
('flying-class', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_example_hevc/main.m3u8', 'hagrid', '@hagrid', 'Rubeus', '🦢', TRUE, 'บินกระดูกกูผู้เจ้าเสียงหึงๆ มาดูกัน 🪂', 'Flight Lesson', 291400, 8730, 31500, 9920, NOW() - INTERVAL '6 minutes'),
('kitchen-cauldron', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_ts/master.m3u8', 'filch', '@filch', 'Argus', '🫕', FALSE, 'ตรวจห้องครัวเสร็จแล้ว หายไปตัวหนึ่ง... เหมือนทุกวัน 🍲', 'Kitchen Loop', 9820, 2330, 401, 88, NOW() - INTERVAL '5 minutes'),
('library-maze', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8', 'melissa', '@melissa', 'Melina', '🦌', TRUE, 'ครั้งแรกที่เดินออกจากห้องสมุดเองได้ ภูมิใจมาก 📜', 'Library Lullaby', 74000, 3260, 15900, 2210, NOW() - INTERVAL '4 minutes'),
('black-cat', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8', 'mrsnorris', '@mrsnorris', 'Censor', '🐈‍⬛', FALSE, 'แมวดำเดินผ่านหน้าหน้าต่างอีกครั้ง เหมือนมีใครซ่อนอยู่ในบ้าน 🐈‍⬛', 'original sound', 189300, 14200, 27400, 7310, NOW() - INTERVAL '3 minutes'),
('quidditch-world-cup', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8', 'oliver', '@oliver', 'Wood', '🏆', TRUE, 'ถ้วยโลกควิดดิชปีนี้ของเราแน่นอน 🏆 #quidditchworldcup', 'Chariots of Fire', 1204000, 88400, 210000, 143000, NOW() - INTERVAL '2 minutes'),
('forbidden-section', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_example_hevc/main.m3u8', 'dumbledore', '@dumbledore', 'Albus', '🧙', TRUE, 'ห้ามเปิดประตูนี้เด็ดขาด ไม่ว่าจะเหตุผลใด 🚫', 'Slow Strings', 87500, 6510, 44100, 18700, NOW() - INTERVAL '1 minute');
